from google.appengine.ext import db

class PostDB(db.Model):
    type             = db.StringProperty()
    title            = db.StringProperty()
    url              = db.StringProperty()
    post_id          = db.IntegerProperty()
    tiny_id          = db.StringProperty()
    content          = db.StringProperty(multiline=True)
    description      = db.StringProperty(multiline=True)
    formatted_description = db.StringProperty(multiline=True)
    snaps            = db.StringProperty(multiline=True)
    author_name      = db.StringProperty()
    author_username  = db.StringProperty()
    author_url       = db.StringProperty()
    votes            = db.IntegerProperty()
    unique_hash      = db.StringProperty()
    published        = db.IntegerProperty()
    created          = db.DateTimeProperty(auto_now_add=True)
    f_created_at     = db.StringProperty()
    f_updated_at     = db.StringProperty()