from google.appengine.ext import db

class PostDB(db.Model):
    type             = db.StringProperty()
    title            = db.StringProperty()
    url              = db.StringProperty()
    post_id          = db.IntegerProperty()
    tiny_id          = db.StringProperty()
    content          = db.TextProperty()
    description      = db.TextProperty()
    formatted_description = db.TextProperty()
    snaps            = db.TextProperty()
    author_name      = db.StringProperty()
    author_username  = db.StringProperty()
    author_url       = db.StringProperty()
    votes            = db.IntegerProperty()
    unique_hash      = db.StringProperty()
    published        = db.IntegerProperty()
    created          = db.DateTimeProperty(auto_now_add=True)
    f_created_at     = db.StringProperty()
    f_updated_at     = db.StringProperty()