application: lmbrrjack
version: 1
runtime: python
api_version: 1

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: public/css

- url: /images
  static_dir: public/images

- url: /js
  static_dir: public/js

- url: .*
  script: main.py
